export { default as Email } from "./email.svg";
export { default as Github } from "./github.svg";
export { default as Linkedin } from "./linkedin.svg";
export { default as Moon } from "./moon.svg";
export { default as Sample } from "./sample.svg";
export { default as Sun } from "./sun.svg";
export { default as Velog } from "./velog.svg";
export { default as Repo } from "./repo.svg";
export { default as VelogDashboard } from "./velogdashboard.svg";
